### GET all issues
@API_URL = http://localhost:3000

GET {{API_URL}}/api/issues
Accept: application/json


### POST new issue
POST http://localhost:3000/api/issues
Content-Type: application/json

{
  "title": "second issue",
  "description": "it's getting serious you guys"
}

### Bad request
POST {{API_URL}}/api/issues
Content-Type: application/json

{
  "title": 12,
  "description": true
}



